Fixes #8
LeComptoirDesPharmacies/offline-plugin pull request #9
Opened 2022-04-06 21:44 UTC by PeterKottas

2026-04-24 15:20 UTC, AntoineDuComptoirDesPharmacies requested changes

2026-04-24 15:20 UTC, AntoineDuComptoirDesPharmacies commented on package.json
> +  "name": "@guestbell/offline-plugin",
You should rollback every change in the package.json file

2026-04-24 15:20 UTC, AntoineDuComptoirDesPharmacies commented on docs/options.md
> +_Default:_ `null`
Put the default minifyOptions here and add it to "default-options.js" file

2026-04-24 15:20 UTC, AntoineDuComptoirDesPharmacies commented on src/service-worker.js
> +    const uglifyOptions = this.minifyOptions
Use options.minifyOptions straight away because default values will be set in default-options.js

2026-04-30 14:26 UTC, b2l commented
As mentioned in https://github.com/LeComptoirDesPharmacies/offline-plugin/issues/8 this fix should not be necessary anymore.
I'm closing the PR. Feel free to reach out if there's anything else breaking for you.

2026-04-30 14:26 UTC, closed without merging